// benefitsSeed.ts — Seed data for a fresh install.
//
// This file is REGENERATED by the quarterly benefits research pipeline.
// Rules for hand edits:
//   • Every benefit MUST cite a real official source_url.
//   • Never break the schema shape below — database.ts imports the exports
//     verbatim.
//   • When a benefit changes, prefer the in-app Quarterly Refresh flow (which
//     records a diff for user review) over editing this file directly.

import type { CardInput, ProgramInput, BenefitInput } from './types';

const FALLBACK_CARDS: (CardInput & { id: string; color_hex: string })[] = [
  {
    id: 'hilton_aspire',
    name: 'Hilton Honors Aspire Card',
    issuer: 'American Express',
    network: 'Amex',
    annual_fee_usd: 550,
    color_hex: '#1e3a8a',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/hilton-aspire/',
  },
  {
    id: 'ihg_premier',
    name: 'IHG One Rewards Premier Credit Card',
    issuer: 'Chase',
    network: 'Mastercard',
    annual_fee_usd: 99,
    color_hex: '#0e7490',
    source_url: 'https://creditcards.chase.com/travel-credit-cards/ihg/premier',
  },
  {
    id: 'amex_platinum',
    name: 'The Platinum Card from American Express',
    issuer: 'American Express',
    network: 'Amex',
    annual_fee_usd: 695,
    color_hex: '#374151',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/',
  },
  {
    id: 'delta_reserve',
    name: 'Delta SkyMiles Reserve American Express Card',
    issuer: 'American Express',
    network: 'Amex',
    annual_fee_usd: 650,
    color_hex: '#7f1d1d',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/delta-reserve/',
  },
  {
    id: 'aa_executive',
    name: 'Citi® / AAdvantage® Executive World Elite Mastercard®',
    issuer: 'Citi',
    network: 'Mastercard',
    annual_fee_usd: 595,
    color_hex: '#4b5563',
    source_url: 'https://www.citi.com/credit-cards/citi-aadvantage-executive-credit-card',
  },
  {
    id: 'marriott_bonvoy_brilliant',
    name: 'Marriott Bonvoy Brilliant American Express Card',
    issuer: 'American Express',
    network: 'Amex',
    annual_fee_usd: 650,
    color_hex: '#78350f',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-brilliant/',
  },
  {
    id: 'marriott_bonvoy_business',
    name: 'Marriott Bonvoy Business American Express Card',
    issuer: 'American Express',
    network: 'Amex',
    annual_fee_usd: 125,
    color_hex: '#92400e',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-business/',
  },
  {
    id: 'hyatt_visa',
    name: 'World of Hyatt Credit Card',
    issuer: 'Chase',
    network: 'Visa',
    annual_fee_usd: 95,
    color_hex: '#0369a1',
    source_url: 'https://creditcards.chase.com/travel-credit-cards/hyatt',
  },
  {
    id: 'ba_visa',
    name: 'British Airways Visa Signature Card',
    issuer: 'Chase',
    network: 'Visa',
    annual_fee_usd: 95,
    color_hex: '#075985',
    source_url: 'https://creditcards.chase.com/rewards-credit-cards/british-airways/visa',
  },
  {
    id: 'virgin_atlantic',
    name: 'Virgin Atlantic World Elite Mastercard',
    issuer: 'Bank of America',
    network: 'Mastercard',
    annual_fee_usd: 99,
    color_hex: '#be123c',
    source_url: 'https://www.bankofamerica.com/credit-cards/products/virgin-atlantic-world-elite-mastercard-credit-card/',
  },
  {
    id: 'citi_prestige',
    name: 'Citi Prestige® Card',
    issuer: 'Citi',
    network: 'Mastercard',
    annual_fee_usd: 495,
    color_hex: '#111827',
    notes: 'Closed to new applicants; existing cardholders retain benefits.',
    source_url: 'https://www.citi.com/credit-cards/citi-prestige-credit-card',
  },
];

const FALLBACK_PROGRAMS: (ProgramInput & { id: string })[] = [
  {
    id: 'delta_medallion',
    name: 'Delta SkyMiles Medallion',
    program_type: 'airline',
    source_url: 'https://www.delta.com/us/en/skymiles/medallion-program',
  },
  {
    id: 'aa_status',
    name: 'American Airlines AAdvantage',
    program_type: 'airline',
    source_url: 'https://www.aa.com/i18n/aadvantage-program/aadvantage-status/aadvantage-status.jsp',
  },
  {
    id: 'ihg_ambassador',
    name: 'IHG One Rewards Ambassador',
    program_type: 'hotel',
    source_url: 'https://www.ihg.com/onerewards/content/us/en/ambassador',
  },
  {
    id: 'marriott_status',
    name: 'Marriott Bonvoy Elite Status',
    program_type: 'hotel',
    source_url: 'https://www.marriott.com/loyalty/member-benefits.mi',
  },
];

// Minimal, hand-verified fallback so a fresh install always shows something
// useful even if the research-generated file is missing. Every benefit here is
// documented in official card pages linked above.
const MINIMAL_FALLBACK_BENEFITS: BenefitInput[] = MINIMAL_FALLBACK_BENEFITS_LIST();

function MINIMAL_FALLBACK_BENEFITS_LIST(): BenefitInput[] { return [
  // Hilton Aspire
  { card_id: 'hilton_aspire', title: 'Free Weekend Night (any category)', category: 'free_night',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 500,
    description: 'Annual free reward night at any Hilton property, any category.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/hilton-aspire/', sort_order: 10 },
  { card_id: 'hilton_aspire', title: '$200 Resort Credit', category: 'hotel_credit',
    reset_cadence: 'semiannual', uses_per_period: 1, value_usd: 200,
    description: '$200 semi-annual statement credit for eligible Hilton Resorts purchases (Jan–Jun and Jul–Dec).',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/hilton-aspire/', sort_order: 20 },
  { card_id: 'hilton_aspire', title: '$50 Airline Credit (per quarter)', category: 'airline_credit',
    reset_cadence: 'quarterly', uses_per_period: 1, value_usd: 50,
    description: '$50 quarterly airline statement credit for eligible airline purchases.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/hilton-aspire/', sort_order: 30 },
  // Amex Platinum
  { card_id: 'amex_platinum', title: '$200 Hotel Credit (FHR / The Hotel Collection)', category: 'hotel_credit',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 200,
    description: 'Up to $200 back on prepaid Fine Hotels + Resorts or Hotel Collection bookings via Amex Travel.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 10 },
  { card_id: 'amex_platinum', title: '$200 Airline Incidental Credit', category: 'airline_credit',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 200,
    description: 'Up to $200 in statement credits per year for incidental fees on one selected airline.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 20 },
  { card_id: 'amex_platinum', title: '$15 Uber Cash (monthly)', category: 'rideshare_credit',
    reset_cadence: 'monthly', uses_per_period: 1, value_usd: 15,
    description: '$15/month Uber Cash for U.S. Uber/Uber Eats orders (+$20 bonus in December).',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 30 },
  { card_id: 'amex_platinum', title: 'Digital Entertainment Credit ($25/mo)', category: 'entertainment_credit',
    reset_cadence: 'monthly', uses_per_period: 1, value_usd: 25,
    description: 'Up to $25/month in statement credits for eligible digital entertainment subscriptions.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 40 },
  { card_id: 'amex_platinum', title: 'Walmart+ Monthly Membership Credit', category: 'retail_credit',
    reset_cadence: 'monthly', uses_per_period: 1, value_usd: 13,
    description: 'Statement credit covering monthly Walmart+ membership fee.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 50 },
  { card_id: 'amex_platinum', title: 'Lululemon Credit ($75/quarter)', category: 'retail_credit',
    reset_cadence: 'quarterly', uses_per_period: 1, value_usd: 75,
    description: 'Up to $75 quarterly at lululemon.com and U.S. Lululemon stores.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 60 },
  { card_id: 'amex_platinum', title: 'Saks Fifth Avenue Credit ($50 x2)', category: 'retail_credit',
    reset_cadence: 'semiannual', uses_per_period: 1, value_usd: 50,
    description: 'Up to $50 semi-annually at Saks Fifth Avenue.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 70 },
  { card_id: 'amex_platinum', title: 'Oura Ring Credit', category: 'wellness_credit',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 200,
    description: 'Up to $200 annual credit toward Oura Ring purchases.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/platinum/', sort_order: 80 },
  // Delta Reserve
  { card_id: 'delta_reserve', title: '$200 Delta Stays Credit', category: 'hotel_credit',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 200,
    description: 'Annual statement credit for Delta Stays hotel bookings on delta.com.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/delta-reserve/', sort_order: 10 },
  { card_id: 'delta_reserve', title: 'Rideshare Credit ($10/mo)', category: 'rideshare_credit',
    reset_cadence: 'monthly', uses_per_period: 1, value_usd: 10,
    description: '$10 monthly statement credit for eligible U.S. rideshare purchases.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/delta-reserve/', sort_order: 20 },
  { card_id: 'delta_reserve', title: 'Resy Credit ($20/mo)', category: 'dining_credit',
    reset_cadence: 'monthly', uses_per_period: 1, value_usd: 20,
    description: '$20 monthly statement credit for Resy-booked restaurant purchases.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/delta-reserve/', sort_order: 30 },
  { card_id: 'delta_reserve', title: '15% Off Award Flight Redemptions', category: 'earning_multiplier',
    reset_cadence: 'unlimited', value_usd: null,
    description: 'Save 15% on Delta award flight redemptions when booking on delta.com.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/delta-reserve/', sort_order: 40 },
  // IHG Premier
  { card_id: 'ihg_premier', title: 'Anniversary Free Night (up to 40k)', category: 'free_night',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 200,
    description: 'Anniversary free night reward valid up to 40,000 points/night (points top-off allowed).',
    source_url: 'https://creditcards.chase.com/travel-credit-cards/ihg/premier', sort_order: 10 },
  // Marriott Bonvoy Brilliant
  { card_id: 'marriott_bonvoy_brilliant', title: '$25 Dining Credit (monthly)', category: 'dining_credit',
    reset_cadence: 'monthly', uses_per_period: 1, value_usd: 25,
    description: '$25 monthly dining statement credit at U.S. restaurants.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-brilliant/', sort_order: 10 },
  { card_id: 'marriott_bonvoy_brilliant', title: 'Free Night (up to 85k)', category: 'free_night',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 500,
    description: 'Annual free night reward valid up to 85,000 points/night.',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/marriott-bonvoy-brilliant/', sort_order: 20 },
  // Delta status
  { program_id: 'delta_medallion', title: 'Regional Upgrade Certificates', category: 'upgrade',
    reset_cadence: 'annual', uses_per_period: 12, value_usd: 100,
    description: 'Choice Benefit: 12 Regional Upgrade Certificates for Diamond members.',
    expiration_note: 'Expire ~Jan 31 of the following program year.',
    source_url: 'https://www.delta.com/us/en/skymiles/medallion-program/choice-benefits', sort_order: 10 },
  { program_id: 'delta_medallion', title: 'Companion Certificate', category: 'other',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 500,
    description: 'Domestic first/main-cabin companion certificate issued at renewal (Reserve card benefit).',
    source_url: 'https://www.americanexpress.com/us/credit-cards/card/delta-reserve/', sort_order: 20 },
  // AA status
  { program_id: 'aa_status', title: 'Systemwide / Global Upgrade', category: 'upgrade',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 500,
    description: 'Loyalty Choice Reward: Systemwide upgrade (Executive Platinum & above).',
    source_url: 'https://www.aa.com/i18n/aadvantage-program/aadvantage-status/loyalty-choice-rewards.jsp', sort_order: 10 },
  // IHG Ambassador
  { program_id: 'ihg_ambassador', title: '2nd Weekend Night Free Certificate', category: 'free_night',
    reset_cadence: 'annual', uses_per_period: 1, value_usd: 300,
    description: 'Ambassador benefit: buy one weekend night, get the second night free at InterContinental properties.',
    source_url: 'https://www.ihg.com/onerewards/content/us/en/ambassador', sort_order: 10 },
  // Marriott status
  { program_id: 'marriott_status', title: 'Suite Night Awards', category: 'upgrade',
    reset_cadence: 'annual', uses_per_period: 5, value_usd: 100,
    description: 'Platinum+ Choice Benefit: 5 Suite Night Awards after 50 nights.',
    source_url: 'https://www.marriott.com/loyalty/member-benefits.mi', sort_order: 10 },
]; }

// Research-generated seed content — replaces the hand-authored fallback lists
// above. Regenerated by scripts/generate_seed.py from benefits-research.json.
import { GENERATED_CARDS, GENERATED_PROGRAMS, GENERATED_BENEFITS } from './benefitsSeedData';

const GENERATED: {
  cards?: (CardInput & { id: string; color_hex?: string | null })[];
  programs?: (ProgramInput & { id: string })[];
  benefits?: BenefitInput[];
} = {
  cards:    Array.isArray(GENERATED_CARDS)    ? GENERATED_CARDS    : undefined,
  programs: Array.isArray(GENERATED_PROGRAMS) ? GENERATED_PROGRAMS : undefined,
  benefits: Array.isArray(GENERATED_BENEFITS) ? GENERATED_BENEFITS : undefined,
};

/** Deterministic color assignment for research-generated cards that don't specify one. */
const DEFAULT_COLORS = ['#1e3a8a','#0e7490','#374151','#7f1d1d','#4b5563','#78350f','#92400e','#0369a1','#075985','#be123c','#111827','#166534','#7c3aed'];
function withColor<T extends { id: string; color_hex?: string | null }>(c: T, i: number): T & { color_hex: string } {
  return { ...c, color_hex: c.color_hex ?? DEFAULT_COLORS[i % DEFAULT_COLORS.length] };
}

export const SEED_CARDS: (CardInput & { id: string; color_hex: string })[] =
  (GENERATED.cards && GENERATED.cards.length)
    ? GENERATED.cards.map(withColor)
    : FALLBACK_CARDS;

export const SEED_PROGRAMS: (ProgramInput & { id: string })[] =
  (GENERATED.programs && GENERATED.programs.length)
    ? GENERATED.programs
    : FALLBACK_PROGRAMS;

export const SEED_BENEFITS: BenefitInput[] =
  (GENERATED.benefits && GENERATED.benefits.length)
    ? GENERATED.benefits
    : MINIMAL_FALLBACK_BENEFITS;
